### ISSUE TITLE
MX_USB_DEVICE_Init()

### ISSUE THREAD

**Issue by krosenba** [skjafar/Portenta_Cube_Template#1]
Hi skjafar,

Thank you for your project.  It has been a nice jump start for my project.

I found by accident that if you change the line in the .ioc file that starts with:
ProjectManager.functionlistsort=

where it has the part about the USB, if you change the text from:
6-MX_USB_DEVICE_Init-USB_DEVICE_M7-false-HAL-false-CortexM7

to:
6-MX_USB_DEVICE_Init-USB_DEVICE_M7-true-HAL-false-CortexM7

then when you re-generate the code, it will remove the call to MX_USB_DEVICE_Init().  So, you don't have to keep removing this from main.c each time you re-build.  By the way, you also need to manually include "usb_device.h" yourself.

Enjoy,
Kevin

**Comment by skjafar** [comment]
Hi Kevin,

I am glad this helped you.

Great find, the ioc file has many options that the GUI may not configure. I'll add that to the repo.

Thank you.
Sofian.
